### PR TITLE
Add support to cross-compile for aarch64

### PR DESCRIPTION
**Pull request by idlethread**
Provide a configuration file and update README.md with instructions to
cross-compile for aarch64 on a x86-host.

### CODE REVIEW

**Comment by connorimes** [comment]
Hi, thanks for your PR.  I generally feel that including cross-compiling configurations in the project source tree is not a good approach.  There are many potential cross-compiling configurations, and we can could never hope to test/maintain them all.  If a user needs to cross compile, they should provide their own configuration or command line parameters to do so -- CMake is good for this, e.g., all the parameters you set in `aarch64.cmake` should be configurable from the command line as well.  Additionally, your cross-compiling configuration appears specific to your system in that it has hard-coded paths in /bin and /usr.

I am curious what your use case is, though.  Is there a compelling reason to want to support aarch64 like you have?  There are many aarch64 cross compilers out there, like for particular custom-built Linux OSes for embedded systems.  Furthermore, the RAPL implementations of the `powercap` interface are really only useful for Intel processors, which are x86-64.  Why are you cross-compiling this project at all?

**Comment by idlethread** [comment]
Hi Connor,

On Mon, Aug 24, 2020 at 6:11 PM Connor Imes <notifications@github.com>
wrote:

> Hi, thanks for your PR. I generally feel that including cross-compiling
> configurations in the project source tree is not a good approach. There are
> many potential cross-compiling configurations, and we can could never hope
> to test/maintain them all. If a user needs to cross compile, they should
> provide their own configuration or command line parameters to do so --
> CMake is good for this, e.g., all the parameters you set in aarch64.cmake
> should be configurable from the command line as well. Additionally, your
> cross-compiling configuration appears specific to your system in that it
> has hard-coded paths in /bin and /usr.
>

I agree this could be improved. Can we atleast patch the README to make it
easier for people to package the tool on aarch64 distributions of OE,
debian?


> I am curious what your use case is, though. Is there a compelling reason
> to want to support aarch64 like you have? There are many aarch64 cross
> compilers out there, like for particular custom-built Linux OSes for
> embedded systems. Furthermore, the RAPL implementations of the powercap
> interface are really only useful for Intel processors, which are x86-64.
> Why are you cross-compiling this project at all?
>

We're working on adding an energy model backend[1] to powercap.

Our target platforms at the moment are all aarch64-based. I noticed you've
removed the rapl-specific tools. Do you know where they will be hosted? We
will have something similar for the energy-model backend too.

[1] https://lkml.org/lkml/2020/7/7/1220
-- 
____________________________________________
Amit Kucheria

**Comment by connorimes** [comment]
Interesting proposal, I'm glad to see power capping work on ARM.  It's too bad the email didn't get any replies, I'm curious what the kernel developer community thinks of it.  I think there are some interesting research projects that could utilize such a capability.

I would not be opposed to documenting cross-compilation in the README (or perhaps just linking to generic instructions on how to cross-compile cmake projects) once there is a need either in upstream linux or in a major fork.  I try to follow the best cmake practices, so there shouldn't need to be any special instructions for cross-compiling -- it should be the same as for any other cmake project using a standard cmake approaches.  If it's not behaving that way, then I'd likely consider that a bug in the build scripts that needs to be fixed.  This should also mean that creating a recipe for OpenEmbedded should be extremely straightforward.  The Debian build infrastructure manages cross-compilation already -- nothing special was needed in the debian packaging setup.

The RAPL-specific tools were removed because they are not needed and they make assumptions that are not holding up as RAPL evolves.  They duplicate the behavior of the more basic tools like `powercap-info` and `powercap-set`, and similarly for the RAPL-specific header files (the `powercap-rapl` header is a special case that I am still undecided on how to proceed with in the long run).  In fact, the only reason they exist at all is because they actually pre-date the more generic tools and headers.  I don't think you should need or want energy-model-specific tools -- instead, use the existing generic ones with the correct control type parameter (e.g., `-p energy_model`); you could always add aliases or wrapper scripts yourself to do this automatically for users in certain environments, but they do not belong in the `powercap` sources.  This `powercap` project code should be "finished" at some point, as these are primarily just bindings, not abstractions that require control-type-specific knowledge which inevitably results in assumptions that do not hold up over time as control type implementations evolve.

There may be benefit in eventually adding a more generic auto-discovery approach like exists in `powercap-rapl`, and I've experimented with it a bit.  There are several hurdles to this, though, such as requiring the powercap library to do more memory management and enforcing a particular structure and access patterns that are not as computationally efficient as we got away with in `powercap-rapl`, which assumes a max tree depth of 2 (one assumption that may not hold in the long run).

**Comment by idlethread** [comment]
> Interesting proposal, I'm glad to see power capping work on ARM. It's too bad the email didn't get any replies, I'm curious what the kernel developer community thinks of it. I think there are some interesting research projects that could utilize such a capability.

We will get the patch reviewed, it has been presented at [ELC](https://ossna2020.sched.com/event/c3Wf/ideas-for-finer-grained-control-over-your-heat-budget-amit-kucheria-daniel-lezcano-linaro) and will be discussed again at LPC this week.

> 
> I would not be opposed to documenting cross-compilation in the README (or perhaps just linking to generic instructions on how to cross-compile cmake projects) once there is a need either in upstream linux or in a major fork. I try to follow the best cmake practices, so there shouldn't need to be any special instructions for cross-compiling -- it should be the same as for any other cmake project using a standard cmake approaches. If it's not behaving that way, then I'd likely consider that a bug in the build scripts that needs to be fixed. This should also mean that creating a recipe for OpenEmbedded should be extremely straightforward. The Debian build infrastructure manages cross-compilation already -- nothing special was needed in the debian packaging setup.
> 
> The RAPL-specific tools were removed because they are not needed and they make assumptions that are not holding up as RAPL evolves. They duplicate the behavior of the more basic tools like `powercap-info` and `powercap-set`, and similarly for the RAPL-specific header files (the `powercap-rapl` header is a special case that I am still undecided on how to proceed with in the long run). In fact, the only reason they exist at all is because they actually pre-date the more generic tools and headers. I don't think you should need or want energy-model-specific tools -- instead, use the existing generic ones with the correct control type parameter (e.g., `-p energy_model`); you could always add aliases or wrapper scripts yourself to do this automatically for users in certain environments, but they do not belong in the `powercap` sources. This `powercap` project code should be "finished" at some point, as these are primarily just bindings, not abstractions that require control-type-specific knowledge which inevitably results in assumptions that do not hold up over time as control type implementations evolve.
>

OK.

> There may be benefit in eventually adding a more generic auto-discovery approach like exists in `powercap-rapl`, and I've experimented with it a bit. There are several hurdles to this, though, such as requiring the powercap library to do more memory management and enforcing a particular structure and access patterns that are not as computationally efficient as we got away with in `powercap-rapl`, which assumes a max tree depth of 2 (one assumption that may not hold in the long run).

Alright, we'll revisit this once we have something merged upstream.

**Comment by connorimes** [comment]
It looks like some of this work is now appearing in the kernel, so congratulations on that!

Regarding the original purpose of this PR, I'm still opposed to including cross-compilation configuration files, but still open to providing some (very light) documentation on how to cross-compile, e.g., linking to general instructions for cross-compiling CMake projects.  Have you tried compiling this repository using a framework like OpenEmbedded?  Certainly we should fix any bugs that might arise, though I don't anticipate any.

I am curious to know more about the new control type(s) though.  For example, I'd like to see a tree (i.e., from the `tree` command) of the /sys/class/powercap filesystem on a device using the new control type.  IIRC, your commit logs in linux seem to indicate that only the tree leaves are real and intermediate nodes are virtual, so I'm curious if there are actually any zone files in the non-leaf nodes.  This has repercussions for this repository in that we currently assume that all nodes in the filesystem tree have zone files, and thus we make no distinction between a tree node's existence and a zone's existence.  This was assumed from the [kernel's powercap documentation](https://www.kernel.org/doc/html/latest/power/powercap/powercap.html), although it's not explicitly stated.  If such a distinction needs to be made, it raises the question of what it means for a tree node to exist but not have a zone?  (Similarly, it would seem that there wouldn't be an constraint files in the non-leaf nodes, although this is less of a problem since we have to actually check for files to verify a constraint's existence.)  In fact, these are questions that ultimately need to be answered about the linux powercap sysfs interface, even if your new control type does have zone files at each tree node.

Cheers.

**Pull request closed without merging**
